### ISSUE TITLE
Error in Trainer

### ISSUE THREAD

**Issue by fay-askari72** [HighCWu/control-lora-v2#6]
Hi, 

It seems the new release of diffusers and controlnet, breaks the trainer with the error below. Is there going to be a fix?

```
/models/controlnet.py", line 807, in forward
 sample, res_samples = downsample_block(
ValueError: too many values to unpack (expected 2)
```

Thank you.

**Comment by HighCWu** [comment]
> Hi,
> 
> It seems the new release of diffusers and controlnet, breaks the trainer with the error below. Is there going to be a fix?
> 
> ```
> /models/controlnet.py", line 807, in forward
>  sample, res_samples = downsample_block(
> ValueError: too many values to unpack (expected 2)
> ```
> 
> Thank you.

I can't find the code you quoted in my code.

**Comment by fay-askari72** [comment]
In your code it would be here:

`/models/controlnet.py", line 807, in forward
    sample, res_samples = downsample_block(
ValueError: too many values to unpack (expected 2)`

the source of which, is the changes in the controlnet module from diffusers that I initially quoted. 
Thank you.

**Comment by HighCWu** [comment]
There is no `line 807` in my [/models/controlnet.py](https://github.com/HighCWu/control-lora-v2/blob/master/models/controlnet.py) , so I can't provide you with any help. If you made changes based on the code in the `diffusers`, you should rewrite the code based on the `diffusers` again, otherwise you should downgrade your `diffusers` to the version that you last successfully ran the code on.

**Comment by fay-askari72** [comment]
Apologies! I was working with the heavily modified version. It is all good. Thank you for your prompt support.
